name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        lisp:
          - sbcl
          - ccl-bin
    env:
      LISP: ${{ matrix.lisp }}

    steps:
    - uses: actions/checkout@v4

    - uses: 40ants/setup-lisp@v4
      with:
        asdf-system: cl-info

    - name: Run tests
      run: |
        echo ${LISP}
