name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
          #- windows-latest
        lisp:
          - sbcl
          - ccl
    env:
      LISP: ${{ matrix.lisp }}

    steps:
    - uses: actions/checkout@v4

    - uses: 40ants/setup-lisp@master
      with:
        asdf-system: cl-info

    - name: Run tests
      run: |
        ${{ env.LISP }} --script ./test/test.lisp
